In [2]:
import pandas as pd

In [33]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
df.head()

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [35]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [37]:
import pandas as pd

c = pd.read_csv(r"C:\Users\karne_dvob0bk\Downloads\coffee.csv")

In [38]:
df.head(10)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [40]:
df.iloc[[0,2]]

   0  1  2
0  1  2  3
2  7  8  9

In [41]:
c.at[0,"Units Sold"]

np.int64(25)

In [42]:
c.sort_values("Units Sold",ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [43]:
df = pd.read_csv("C:/Users/karne_dvob0bk/Downloads/bios.csv")

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 11.1 MB

In [45]:
df.loc[df['height_cm']>215,['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [46]:
df[df['name'].str.contains("Keith") & (df['born_country']=="CAN")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
29308,29524,Keith Carter,1952-10-16,Winnipeg,Manitoba,CAN,Canada,155.0,51.0,NaN
29322,29538,Allan Keith,1889-02-22,Toronto,Ontario,CAN,Canada,NaN,NaN,1953-11-21
33832,34095,Keith Morgan,1973-11-12,Calgary,Alberta,CAN,Canada,178.0,98.0,NaN
35839,36123,Keith Donald,1940-09-23,Vancouver,British Columbia,CAN,Canada,190.0,83.0,NaN
41171,41486,Keith Elder,1940-07-14,Brandon,Manitoba,CAN,Canada,173.0,73.0,NaN
63693,64173,Keith Wilson,1937-11-26,Montréal,Québec,CAN,Canada,177.0,70.0,NaN
84923,85601,Keith Fair,1968-01-08,Castlegar,British Columbia,CAN,Switzerland,180.0,83.0,NaN
96707,97485,Keith Shepherd,1947-10-21,Waskesiu Lake,Saskatchewan,CAN,Canada,NaN,NaN,NaN
98236,99030,Keith Woodall,1926-08-04,Elmira,Ontario,CAN,Canada,NaN,NaN,1981-05-17
99754,100553,Keith Primeau,1971-11-24,Toronto,Ontario,CAN,Canada,193.0,95.0,NaN
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN
108831,110002,Sandra Keith,1980-12-11,Ottawa,Ontario,CAN,Canada,170.0,55.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN

In [47]:
c['Price']=4.66
c.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.66
1     Monday       Latte          15   4.66
2    Tuesday    Espresso          30   4.66
3    Tuesday       Latte          20   4.66
4  Wednesday    Espresso          35   4.66

In [48]:
import numpy as np

In [49]:
c['New Price']=np.where(c['Coffee Type']=='Espresso', 3.99,5.99)
c.head()

         Day Coffee Type  Units Sold  Price  New Price
0     Monday    Espresso          25   4.66       3.99
1     Monday       Latte          15   4.66       5.99
2    Tuesday    Espresso          30   4.66       3.99
3    Tuesday       Latte          20   4.66       5.99
4  Wednesday    Espresso          35   4.66       3.99

In [50]:
c.drop(columns=['Price'],inplace=True)

In [51]:
c

          Day Coffee Type  Units Sold  New Price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [52]:
c['Sales']=c['New Price']*c['Units Sold']

In [53]:
c

          Day Coffee Type  Units Sold  New Price   Sales
0      Monday    Espresso          25       3.99   99.75
1      Monday       Latte          15       5.99   89.85
2     Tuesday    Espresso          30       3.99  119.70
3     Tuesday       Latte          20       5.99  119.80
4   Wednesday    Espresso          35       3.99  139.65
5   Wednesday       Latte          25       5.99  149.75
6    Thursday    Espresso          40       3.99  159.60
7    Thursday       Latte          30       5.99  179.70
8      Friday    Espresso          45       3.99  179.55
9      Friday       Latte          35       5.99  209.65
10   Saturday    Espresso          45       3.99  179.55
11   Saturday       Latte          35       5.99  209.65
12     Sunday    Espresso          45       3.99  179.55
13     Sunday       Latte          35       5.99  209.65

In [54]:
c=c.rename(columns={'New Price':'Price'})

In [55]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [56]:
df['height category']=df['height_cm'].apply(lambda x:'Short' if x<165 else('Average'if x<185 and x>165 else 'Tall' ))

In [57]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [3]:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D", "E"],
    "Runs": [500, 250, 600, 300, 100],
    "Wickets": [5, 20, 8, 25, 30]
})

df["All_Rounder_Score"] = df["Runs"] + df["Wickets"] * 20

print(df.sort_values("All_Rounder_Score", ascending=False))

  Player  Runs  Wickets  All_Rounder_Score
3      D   300       25                800
2      C   600        8                760
4      E   100       30                700
1      B   250       20                650
0      A   500        5                600